service: tokens

useDotenv: true

provider: 
  name: aws
  runtime: nodejs16.x

functions:
  tokens:
    handler: src/tokens.handler
    events: 
      - httpApi: POST /tokens
  token:
    handler: src/token.handler
    events: 
      - httpApi: POST /token
        
custom:
  esbuild:
    bundle: true
    minify: true

plugins: 
  - serverless-offline
  - serverless-esbuild